include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/icons/**

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true
    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    # prefer_double_quotes: true
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true
    # I think it's easier to read if they are grouped together
    sort_pub_dependencies: true
