name: troisplay
description: Troisplay Mobile

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  badges: ^1.2.0
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  firebase_messaging: ^7.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^4.0.1+2
  flutter_paystack: ^1.0.4+1
  flutter_svg: ^0.19.3
  fluttertoast: ^7.1.8
  get: ^3.26.0
  get_storage: ^1.4.0
  intl: ^0.16.1
  ionicons: ^0.1.1
  shimmer: ^1.1.2
  sliding_up_panel: ^1.0.2
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/images/
    - assets/icons/
